# 自定义配置
alita:

# web配置
server:
  port: 8080                                 # web服务端口
  servlet:
    context-path: /                          # web上下文路径
  tomcat:
    accept-count: 1000                       # 当所有可能的请求处理线程都在使用时，连接请求的最大队列长度
    max-connections: 5000                    # 服务器在任何给定时间内接受和处理的最大连接数。达到上限后，操作系统仍可根据 "acceptCount"属性接受连接
    threads:
      max: 500                               # 工作线程的最大数量
      min-spare: 50                          # 最少工作线程数

# spring配置
spring:
  profiles:
    active: dev                              # 使用指定的配置文件：application-dev.yml
  servlet:
    multipart:
      max-file-size: 10MB                    # 单个文件大小
      max-request-size: 20MB                 # 总上传大小
  thymeleaf:                                 # ThymeLeaf配置
    cache: false                             # 是否开启页面缓存功能
    prefix: classpath:/templates/            # 模板前缀
    suffix: .html                            # 模板后缀


# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.alita.*.domain

# jwt配置
jwt:
  header: Authorization                      # header名称
  secretKey: 1a!2b@3c#4d$5e%6f^              # jwt加密密钥
  expired: 30                                # jwt令牌过期时间


